### ISSUE TITLE
bookmarks order is wrong

### ISSUE THREAD

**Issue by lazymonkey2** [floccusaddon/floccus#1110]
### Which version of floccus are you using?

4.12.0

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using?

chrome 100.0.4896.75 and edge 100.0.1185.29

### Describe the Bug

the order of the bookmarks is wrong. I noticed this in the bookmark toolbar, which contains most of my bookmarks.
on chrome I have bookmarks sorted in a certain order, and on edge they are not in the same order (but as far as I know all the bookmarks are correctly synchronized).

### Expected Behavior

I want to have the same bookmark order in chrome and edge.
If I add a new folder or bookmark, and reorder manually my bookmarks on chrome I expect that the same order will be synchronizrd to edge (and viceversa).

### To Reproduce

I believe that the issue is floccus not working correctly on edge.
Synching between chrome browsers seems to work correctly.

Here is a screenshot of bookmarks on chrome:
![chrome](https://user-images.githubusercontent.com/26486758/161705692-f5cea38c-b50c-432f-87e6-203f0b611e43.png)

And here is for edge:
![edge](https://user-images.githubusercontent.com/26486758/161705795-f774be01-5a23-4596-b9bc-5f2ae9ae63de.png)

On edge the "windows" folder is ok, but the "wls" folder is not: it should be next to "windows".
I had issues too with the placement of the three bookmarks on the right.

Please note that the "tj cookie" is a special chrome bookmark:
chrome://settings/content/all?searchSubpage=tj-&search=cookie
that I use to easily delete the local cookies on my pc (maybe this could be a problem while syncing?).

The other two bookmarks are links to pages of an app running on my pc, and they are similar to this one:
https://tj-xxxxxxxxxxxx:9447/srv-rest/login.html

I attach the anonymozed logs for chrome and edge.

[chrome.zip](https://github.com/floccusaddon/floccus/files/8416175/chrome.zip)

[edge.zip](https://github.com/floccusaddon/floccus/files/8416174/edge.zip)

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mh. Does it help to "download & override once"?

**Comment by 424344** [comment]
I've done the download and override, but it didn't fix the order.
however in the logs there is this error:

2022-04-06T09:30:13.716Z Failed to execute REORDER: Failed to reorder folder 24909: Index out of bounds.
Moving on.
2022-04-06T09:30:13.716Z [b4bc489c94b9919ac857078fbfd423ea4bb30ba7489abcbf14374f9e49f9b5c9]
2022-04-06T09:30:13.843Z Failed to execute REORDER: Failed to reorder folder 24920: Index out of bounds.
Moving on.
2022-04-06T09:30:13.843Z [bc1b1f1380c84383540224c8fd3ecc1f43aebf8ffc56edbd33ec37e1e813e37c]
2022-04-06T09:30:13.974Z Overriding title of built-in node 1 Favorites bar => Bookmarks Bar
2022-04-06T09:30:14.053Z onSyncComplete
2022-04-06T09:30:14.268Z No changes to the server version necessary
2022-04-06T09:30:14.764Z Successfully ended sync process for account Google Drive: bookmarks.xbel

I think that in case of errors like "Index out of bounds" floccus should give a warning to the user, not fail silently.

I have attached the logs (I have done the override two times, so there are two logs)
[anonymized_logs_after_override.zip](https://github.com/floccusaddon/floccus/files/8425647/anonymized_logs_after_override.zip)

**Comment by 424344** [comment]
I have investigated a little, and have found differences in the bookmarks of edge and chrome.
1) on edge in the folder 24909 and 24920 there are two missing bookmarks, which are present in chrome. Maybe during the sync these two bookmarks are detected, but edge fails to create them, and then I get the index out of bounds error, and the reorder could be failing because of that.
2) for unknown reasons in chrome there is a bookmark "edge://policy/" that is missing in edge! Since it starts with edge:// it was added in edge for sure, then it was synced to chrome (possibly in a previous version of floccus that didn't block these special bookmarks) and then I don't know what happened but it's strange that now it is missing in edge. Probably there could be similar issues for special bookmark for Brave, Vivaldi, and others.

**Comment by FrankBKK** [comment]
I have the same problem - I use the Firefox bookmark toolbar on my main pc as upload only reference and all other pc and browsers (Firefox, Opera, Chrome, Edge) as download only so they are in sync with my main browser - since the latest Floccus updates the sorting is all messed up on the download clients and I had to resort to another bookmark sync and disabled Floccus auto-sync. 
Hope this can be fixed soon ...

**Comment by pinpontitit** [comment]
Same for me. Sometimes after sync, the bookmarks on the downloading platform are all messed up. As I dont have so many, I sort them manually but if I had a lot I would be unhappy.

**Comment by 424344** [comment]
In my case after sync there are some missing bookmarks. I suspect that the wrong order is a consequence of these missing bookmarks. Can you open the logs and look for some error like "index out of bounds exception" ?
Maybe you could also upload here your anonymized logs, to help the author resolving the issue.

**Comment by pinpontitit** [comment]
Ok I'll upload one in a day or two.
but now I am certain:
I don't have any bookmark that is deleted, but the bookmarks are sorted differently sometimes.

Once again a bookmark which in my browser I did put in fifth position, had become first position in Android.
And syncing in my browser or Android doesnt change having.
thats strange

**Comment by Eyion** [comment]
So has the problem been solved

**Comment by pinpontitit** [comment]
It happened again tonight.
I opened Floccus 10 min ago and discovered that the bookmarks order had changed since I had opened it maybe 20 minutes ago. So thats why I did notice the change.

I'm pretty sure what happened is:
the 2 last bookmarks on my bookmark list were moved in first position.
I did add those bookmarks yesterday in my computer browser so they were in last position of my toolbar.

Now they are in first position of (Android) bookmarks, so I guess that tomorrow when I will sync my computer browser floccus, they will be moved to the first position of my toolbar.

I am sure they were at the end in browser. But I am not sure they were already synced in Android, and after a second or third sync, Android moved them to first position. Or if they were'nt synced and the first sync made them appear to first position.

I wish I had look with more attention... but thats life.

I cannot download debug logs for the reason stated in my other issue #1181 

thanks

**Comment by 424344** [comment]
I tested again using v4.14.0 but still doesn't work.
After sync I also have missing bookmarks, but I don't know if the wrong order is related to these missing bookmarks.

**Comment by marcelklehr** [comment]
> One bookmark ("MDN") was replaced by "gitflow commands".

That's concerning. Did the URL also change on this bookmark or is it still pointing to MDN?

> I forgot to download log yesterday, if I go download today will it still contains infos about yesterday ?

You can try. It might not contain yesterday's entries anymore.

Can you check whether your XBEL file also contains the mistakes?

**Comment by FrankBKK** [comment]
same problem here - the sorting is just garbled up - I sync between many PC (with one being the master) and I get now different results on different PC - really annoying - as a result  (hopefully) temporarily I now have to use another sync SW

**Comment by FrankBKK** [comment]
btw - there is an easy way to test that - in the bookmark toolbar of any browser add a new entry and rename it with the current date - its easy to spot when you sync/download on another PC that it changes position - happens on 100% of my computers

**Comment by marcelklehr** [comment]
Thanks! I will try to replicate.

**Comment by marcelklehr** [comment]
I was able to reproduce and find the bug.

**Comment by marcelklehr** [comment]
The problem was only present in the root of the synced folder due to a copy-paste error :see_no_evil:

**Comment by marcelklehr** [comment]
I will do a release shortly.

**Comment by pinpontitit** [comment]
> The problem was only present in the root of the synced folder due to a copy-paste error :see_no_evil: 

Hi
The disorder of bookmarks continue happening for me in the root folder (i.e. "Bookmarks bar" for me).

I'm quite sure the Android version of Floccus is in cause.
I can add, remove, sync from one browser to another browser, without the order being change.
But sometimes after syncing with Android, if I come back to browser, the last 5 bookmars on my bookmark bar comme yo the front.

It seems to happen after syncing in android, directly the next sync on browser.

Maybe it happens only when new bookmarks were added, if they were old bookmarkd the order is not compromise.

I'm not 100℅ sure but I'm sharing anyway if it can help debug.

Can I ask you something: which file contains the code responsible for syncing and sorting bookmarks when syncing in Android ?

thanks

**Comment by marcelklehr** [comment]
ping @pinpontitit

**Comment by pinpontitit** [comment]
Hi 😀

``` Does it help to "sync down" once on Android to get the intended order onto your android device and then set sync strategy back to merge? ```

I never tried because I was affraid to lose the new bookmarks added to Android if I did that...

If I add bookmarks in Android, and then after, in order to sync Android with browsers, I start by doing a "sync down" (or pull), am I right that this will erase all the new bookmarks ?

By the way, the bookmarks order problem happened again few days ago:
I spent most of the time on my computer, syncing between firefox and chrome, and then when, after almost a month without syncing with my phone, I synced in Android, all the bookmarks were saved in disorder.
All of that to say I'm quite positive its an Android sorting problem.

**Comment by marcelklehr** [comment]
> If I add bookmarks in Android, and then after, in order to sync Android with browsers, I start by doing a "sync down" (or pull), am I right that this will erase all the new bookmarks ?

Ah, that might be a problem, yes :/

**Comment by pinpontitit** [comment]
Sorry, Is there something I could do to help debug this ?
Any procedure you're thinking of ?

Would it help if I did the same thing (adding bookmarks in Android and browsers without syncing Android, during 1 week, and then sync in Android)
 and if the problem occurs again, post here the logs (even if I doubt there's infos in the logs about the ordering process) ?

**Comment by marcelklehr** [comment]
It could help, yes, make sure to upload the logs [to my nextcloud](https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw), though, if you want privacy ;)

**Comment by neoKushan** [comment]
Hi, I am not sure if this is related or not to the above issue. I am a new user to Floccus, syncing via nextcloud. My intention is to sync bookmarks between Firefox and Chrome. 

Everything works but folders are out of sync. Bookmarks themselves are in the correct order, but any folders are going to the bottom instead of their correct order. 

The bookmarks _within_ folders are in the correct order, it's just the folders themselves. 

I am not syncing with Android or anything yet.

**Comment by marcelklehr** [comment]
Hi @neoKushan, please open a new issue and fill out the details about your setup so I can help better and judge if this is indeed a duplicate :)

**Comment by neoKushan** [comment]
@marcelklehr Thanks for the response! Weirdly enough, this issue has just abruptly fixed itself. I promise I didn't do anything different, I had given up trying to fix it while waiting for a response and during the next automated sync it just reordered everything. Apologies for the bit of a time waste, but if it reproduces I'll open a new ticket.

**Comment by 424344** [comment]
Still not fixed, I have experienced this issue just last week. 
Please reopen.

**Comment by dylandea** [comment]
@marcelklehr 
> It could help, yes, make sure to upload the logs [to my nextcloud](https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw), though, if you want privacy ;)

Yes still not fixed.
It happened to me twice this week.

So I have new informations:

On the contrary of what I was saying before, it seems to have nothing to do with the Android App: I didnt use the app since one or two weeks.

But I am currently using my two desktop browsers Chrome and Firefox, everyday, at the same time, jumping from one to another every 5 minutes or so (I know that's strange but I do that for various reasons).

And while jumping from one to another, I might save a bookmark in Chrome, then save another one in Firefox, etc. 
So maybe this problem is related with the famous 30minutes timestamp/lockfile stuff, but I don't really know.

So it happened earlier this week. The last 3 bookmarks on my toolbar where moved to the beginning of the toolbar. I think they were the last ones, I am not 100% sure, but I'm positive that those bookmarks were saved very recently, like the same day.
It was 3 Amazon.com bookmarks, in case you can see them in the logs, but nowaday I deleted them because I didnt need them anymore.

However it just happened again, no more than 1 hour ago, maybe 2h ago.
So when I noticed, I directly donwloaded the logs from both Chrome and Firefox, and sent them to the link you provided.

**Let me know if you received them!**

Again, it's the three last bookmarks that were moved and became the three first bookmarks on my toolbar.
the bookmarks are:
-github: shadowwalker/next-pwa
-github: next-js/example...
-a Medium.com article about building a pwa with Next.js

They still are in first position in case you can see them in the logs.

**Another important thing:**
I always thought that the problem was only the 3 last bookmark that go to first position.
But it's not only that because I also noticed, during this week, that one of the last bookmarks on my toolbar, like the third or fourth bookmark before the last one, was something I saved some months ago, the bookmark is this one:

"           L’explication des opérateurs de recherches Google |  Brandwatch      "  exactly wrote like that with the spaces before and after.
And the link:
https://www.brandwatch.com/fr/blog/lexplication-des-operateurs-de-recherches-google/

And before this bookmark, there are a lot of bookmarks I saved recently. So i knew, and anyway I remember, that this bookmark is a very old one.

So this means that, not only the three last bookmarks, but also other bookmarks are impacted by this problem of order changing.
So the "pattern" of this bug is not clear to me.
However it's nice to observe that this pattern of three last to first place is repeating itself, and like I said twice this week.

Hope this helped!

**Comment by dylandea** [comment]
@424344
> Still not fixed, I have experienced this issue just last week. Please reopen.

Do you remember how it happened ?
Was it similar with me (the last 3 bookmarks to first position) or something else ?
In the Toolbar or in another root folder ?
Folder order was it impacted also, or only bookmarks?

Thanks

**Comment by 424344** [comment]
This issue has recently happened while syncing from firefox to gdrive. I have noticed it in the bookmark toolbar.
I have configured firefox to only upload (push up), and chrome to only download bookmarks (pull down).
so there is no merge of bookmarks.
I think that the issue is when reading bookmarks and generating the xbel file, because it seems to me that the bookmarks file on gdrive has wrong bookmarks order: in firefox there is a folder which is the first in the bookmarks bar (far left), while in the xbel file it is found in the middle of the file, not at the start. I believe this is wrong.

**Comment by dylandea** [comment]
I've checked the log files I sent you Marcel and I noticed that it only stores the last sync that happened.
On the log file, I can see that the 3 first bookmarks already are the ones that were moved from end to beginning of the bar, 1h hour before or so.
So I don't know how it can help you to debug...

If it happened one hour ago, and by the time I notice, others sync happened, it means that the log file was overwritten with the new sync.

It would be better if the log file stored by default many syncs, no ?

**Comment by dylandea** [comment]
Ok it happened just now and I downloaded directly the log (floccus-4.17.1-2022-11-12). I send it to you now.

I was making tests to see if renaming a folder in Firefox would also rename it in Chrome.
So, in Firefox, I renamed the folder that was called "Quick" (#882) by "Quicc". (This folder is at the very beginning of the old logs I did sent you)

Then I went on Chrome and changed Floccus behavior with "Pull Down".

The folder was immediatly moved to the penultimate position of the Bookmark bar, and was correctly renamed Quicc.

You can see it in the new log as "Quicc" #891.

It seems that renaming a folder also changes his ID, and also all the ID's of the bookmark it contains.

Why ? Is it necessary ?

Also the parent ID that was 1 changed and became 0.

**Comment by marcelklehr** [comment]
> It seems that renaming a folder also changes his ID, and also all the ID's of the bookmark it contains.

That's not the case from the logs you sent me. The reason is that items have different IDs on each device and floccus maps between them. So, it's important to know if it's a local item or a server item to judge whether the ID changed.

**Comment by marcelklehr** [comment]
In your case for some reason no mappings / cache were available to indicate that Quick and Quicc referr to the same folder, so Quick was removed and Quicc was created.

**Comment by marcelklehr** [comment]
> It would be better if the log file stored by default many syncs, no ?

That's tough as the logs are quite lengthy and I'm already happy the browser allows storing logs from one run :/

**Comment by 424344** [comment]
Hello, any news?
I'm still experiencing this issue when syncing between different browsers (using gdrive).

As an example I sync from edge (push up) to firefox (pull down) and for some bookmarks in firefox I get different order from the one in edge.
Then I sync (pull down) in chrome using the same xbel on gdrive I used before (the one from edge) and in chrome I get bookmarks with different order than the one in edge, but this time the (wrong) order in chrome in different from the (wrong) order in firefox.

so now I have three set of bookmarks in edge, firefox and chrome, all with different order.

maybe there is some difference when parsing the xbel file on the various browsers?

**Comment by 424344** [comment]
I just checked the firefox console (ctrl+shift+j) and I see many logs like this one:

10:34:19.448 2023-01-25T09:34:19.448Z Failed to execute REORDER: E012: Folder ordering is missing some of the folder's children Moving on. background-script.js:2:22822

could this be related to this issue?

**Comment by dylandea** [comment]
Yes the problem was not solved for me, so I changed my way of working:
Instead of putting a lot of bookmarks directly in the root folder (which was Bookmarks Bar in my case), I created only one Folder in the root (still Bookmark bar), and I put all the rest inside this folder.

And I think everything keeps the right order inside this folder.
I think... I am not 100% sure.

I think it was related
-or with working on the root (Bookmark bar or whatever folder you choose as root) 
-or with working specifically on the Bookmark Bar (and the way Bookmark bar is handled is different on each browsers ?)

**Comment by dylandea** [comment]
Can I ask you what is the root folder you chose in the Floccus settings ?

**Comment by 424344** [comment]
I'm syncing the toolbar only. 
I have many folders in the toolbar, and each folder has many subfolders and bookmarks.
I don't want to move all my folders and bookmarks into a single folder in the toolbar. 
I find it incovenient for me.

Are you using floccus to sync between different browsers? I'm currently syncing from edge to firefox and to chrome, but sometimes I change the "source" browser. In all cases I got wrong order, in both the root folder and in subfolders. 
Sometimes it affects only a few bookmarks, and sometimes a "block" of bookmarks (like a number of bookmarks appears to be moved in a different location in the bookmark tree).

**Comment by dylandea** [comment]
> I don't want to move all my folders and bookmarks into a single folder in the toolbar. 
> I find it incovenient for me.
Indeed...

> Are you using floccus to sync between different browsers? 
Yes between Firefox and Chrome. Both are in "Merge" config.

> In all cases I got wrong order, in both the root folder and in subfolders. 
Ok so your subfolders are also in disorder. That's odd, I don't think it happened to me (I never noticed it).

**Comment by 424344** [comment]
just happened again (v4.18.1):
I have created a new folder in the toolbar as first folder (folder0), which contains other 4 folders (folder1, folder2, folder3, folder4).
I did a push up on edge, and a pull down on firefox.
now firefox has the folder0 in the toolbar, in the right place, but the sub folders are in reversed (folder4, folder3, folder2, folder1).
the contents of the folders are only bookmarks, and are in the correct order.
I also did a pull down on chrome, and this time the folders were correctly synchronized (not always the case).

**Comment by marcelklehr** [comment]
> I didn't try with the same browsers, but that shouldn't be an issue, I think. The code is the same.

hah. M**th\*rf\*ck.

[Screencast from 20.03.2023 15:17:46.webm](https://user-images.githubusercontent.com/986878/226368056-f3c233fc-f3ba-4157-aab0-1aedf0841515.webm)

**Comment by 424344** [comment]
so is it fixed?

**Comment by marcelklehr** [comment]
The issue you reported here https://github.com/floccusaddon/floccus/issues/1110#issuecomment-1413400949 is fixed now. The next release will have the fix. :)

**Comment by 424344** [comment]
Just tested v4.19.1 and it still syncs with wrong order.

**Comment by marcelklehr** [comment]
hrm.

Can you still reproduce with these steps? Could you upload the logs again to my file drop? 

> I have created a new folder in the toolbar as first folder (folder0), which contains other 4 folders (folder1, folder2, folder3, folder4).
> I did a push up on edge, and a pull down on firefox.
> now firefox has the folder0 in the toolbar, in the right place, but the sub folders are in reversed (folder4, folder3, folder2, folder1).

**Comment by 424344** [comment]
Hello,
I reproduced a similar issue with just two folders.
- I have two folders at the end (right) of the toolbar: folder1 and folder2.
- I push up from the origin browser.
- I verify the xbel in gdrive: the order is correct
- I pull down on the destination browser
- the order is wrong: the two folders are swapped: folder2 then folder1
- I pull down again on the destination browser without doing anything else
- the order now is correct!

Here are the logs for the first and second try.

[floccus-4.19.1-2023-04-05-first-try-ko.log](https://github.com/floccusaddon/floccus/files/11159685/floccus-4.19.1-2023-04-05-first-try-ko.log)

[floccus-4.19.1-2023-04-05-second-try-ok.log](https://github.com/floccusaddon/floccus/files/11159689/floccus-4.19.1-2023-04-05-second-try-ok.log)

**Comment by 424344** [comment]
any news on this issue?
I have done some more testing and wrong bookmarks order still happens, even in nested folders, not just in the toolbar.

**Comment by SchwarzerA** [comment]
Floccus is unfortunately now rather unreliable.

I'm using v4.19.1 (always the last available) on Linux, iOS, Android and Windows with FireFox, Chrome and Edge. Data is stored as an xbel file on a private webdav area. Until now I've run it in merge config but the errors appear also on upload. I noticed that multiple times the bookmarks are jumbled up and it happened from FF to Edge and vice versa and also from Windows to Linux. 

Most irritating is that Floccus seems to be especially concerned with bookmarks like 

- about:about
- chrome://chrome-urls
- edge://edge-urls
- and similar

it even refuses to upload them initially! Does anyone have a clue how to diagnose that? Or even a hint what to do?

**Comment by RobertZenz** [comment]
I seem to be able to reproduce the wrong order in the bookmarks toolbar at will.

Setup is Floccus V4.19.1 with NextCloud 25, Bookmarks 12.1.0. I've configured the account in Floccus, disabled automatic synchronization and set a (empty) server folder (`/Browser`). When I now do "Push Up Once" all bookmarks are being synchronized, including the bookmarks toolbar. However, the order of at least the toolbar is completely messed up. Additionally, one of the bookmarks gets renamed (address gets appended in parentheses to the name). After pressing "Sync Now" (set to "Merge") the order is corrected on the server. However, I believe that when I let it synchronize automatically in the background the incorrect order is synchronized back to my machine (that was how I first found this).

I wouldn't exactly rule out that this might be a bug in the Bookmarks version I'm using, though, as the order of the menu is always correct in the log. Shall I upload the full log of the "Push Up Once" synchronization to the above mentioned NextCloud share or is the redacted enough?

**Comment by RobertZenz** [comment]
> Additionally, one of the bookmarks gets renamed (address gets appended in parentheses to the name).

I think I know what that is, duplicate bookmarks get "unified" to a single name the first time the synchronization happens. So if I have two bookmarks pointing to the same address, in two different folders each bookmark with a different name, they will be "unified" to one name. Which I'm not sure, though, but it seems like the name of the first encountered bookmark is used.

As far as I can see, that does **not** seem to be a problem of Floccus, though. according to the log it *did* send the bookmarks correctly but the server seems to have screwed with them.

---

I think a good way to avoid this issue would be:

 1. Set up the account in the preferences.
 2. Disable automatic sync.
 3. Set the account to "Push up".
 4. Perform "Push up once".
 5. Wait for it to complete.
 6. Perform "Push up once" a second time.

The bookmarks should now be correct on the server and automatic synchronization *should* work from here on, I haven't tested it, though.

**Comment by marcelklehr** [comment]
> So if I have two bookmarks pointing to the same address, in two different folders each bookmark with a different name, they will be "unified" to one name.  [...] that does not seem to be a problem of Floccus

Yes, that's Nextcloud Bookmarks doing.

**Comment by marcelklehr** [comment]
> When I now do "Push Up Once" all bookmarks are being synchronized, including the bookmarks toolbar. However, the order of at least the toolbar is completely messed up. [...] After pressing "Sync Now" (set to "Merge") the order is corrected on the server (I see the correct order in Bookmarks when set to "Manual Order").

I think this should be fixed in the latest version now, I've discovered that the Unidirectional sync strategy didn't use the ID mappings which could cause problems when applying orderings. Can you try this again with floccus v5.1.1?

**Comment by RobertZenz** [comment]
Ordering of the initial synced bookmarks is still messed up with 5.1.1., an additional sync still fixes it, though.

That is with automatic synchronization disabled:

 1. Deleting all bookmarks on the server.
 2. Pressing "Push up once"

**Comment by marcelklehr** [comment]
Alright. I'll look into this again then

**Comment by marcelklehr** [comment]
@RobertZenz I cannot seem to reproduce this. I tried the following

1. Create profile for local:/Bookmarks bar -> server:/
2. Create 10 bookmarks, put one folder at 3rd position
3. Delete all bookmarks in Nextcloud
4. Push up once
5. Order in Nextcloud is as expected

**Comment by lazymonkey2** [comment]
Hello, thanks for working on this.
However I'm using Google Drive, not NextCloud.
I'm also using different browsers (Firefox, Edge, Vivaldi).
Maybe your test environment is not accurate to reproduce the issue?

BTW I've got thiss issue just two weeks ago, so still a problem for me.

**Comment by marcelklehr** [comment]
v5.2.4 should fix this now. Feedback is appreciated :heart:

**Comment by RobertZenz** [comment]
I cannot reproduce it anymore, so that's fixed for me.
