### ISSUE TITLE
No more automatic sync / Scheduled: This profile will be synced soon

### ISSUE THREAD

**Issue by misterhsp** [floccusaddon/floccus#1495]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Which version of Nextcloud? (if relevant)

27.1.5

### What kind of WebDAV server are you using? (if relevant)

 Nextcloud

### Describe the Bug

Since the last update of floccus the synchronization does not work automatically after starting the browser. It only works when I click on the small icon at the top right. Before everything was automatic. Has this been changed?

### Expected Behavior

 '

### To Reproduce

Since the last update of floccus the synchronization does not work automatically after starting the browser. It only works when I click on the small icon at the top right. Before everything was automatic. Has this been changed?

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank your for the feedback!
I can confirm this. The underlying cause is that Manifest v3 background scripts are terminated rather aggressively by the browser which causes the sync process to be interrupted. :/

**Comment by misterhsp** [comment]
Can you change that in floccus or do I have to put up with it?


/hsp








Am 24.12.23 um 15:26 schrieb Marcel Klehr:

**Comment by marcelklehr** [comment]
Oh, yes, I will try to fix this, of course!

**Comment by marcelklehr** [comment]
One idea is to let the sync process run in a visible open tab or window instead, but that's rather ugly :/

**Comment by marcelklehr** [comment]
This should finally be fixed with v5.0.6 released just now -- please report back :heart:

**Comment by misterhsp** [comment]
Danke, funktioniert wieder.


/hsp




Am 31.12.23 um 19:24 schrieb Marcel Klehr:

**Comment by misterhsp** [comment]
upd, sorry ...  german


Thanks, it's working again.


/hsp


Am 01.01.24 um 10:34 schrieb Holger Schröder:

**Comment by jdelker** [comment]
Looks good so far.
It may be worth noting, that you need to upgrade **all** of your clients before this is actually working properly.
Any <5.0.6 client will again create that orphaned lock situation again and block all others.

**Comment by truthsword** [comment]
Uninstalled, reinstalled now on 5.0.6 and this issue remains. Cant force sync up to webdav server. No sync for the past two weeks.

**Comment by misterhsp** [comment]
I can't confirm that. For me the sync with webdav (Nextcloud / xbel
file) works again.


Am 01.01.24 um 19:13 schrieb truthsword:

**Comment by marcelklehr** [comment]
@truthsword Make sure all your firefox instances have v5.0.6, you may have to delete a surplus lock file on your webdav share.

**Comment by truthsword** [comment]
> @truthsword Make sure all your firefox instances have v5.0.6, you may have to delete a surplus lock file on your webdav share.

This was it. Had to uninstall the extension from all clients, and delete the lock file.

Would be nice to have notifications when sync fails (mine happened 2 weeks ago). Maybe I've missed that in the settings.

**Comment by marcelklehr** [comment]
> Would be nice to have notifications when sync fails

Usually you will be notified of failure, this was an extraordinary situation, because I changed the API platform. This is unlikely to happen again soon.

**Comment by albirs** [comment]
> @truthsword Make sure all your firefox instances have v5.0.6, you may have to delete a surplus lock file on your webdav share.

where is that lock file located in an nextcloud instance ...?

**Comment by marcelklehr** [comment]
@albirs if you are using Nextcloud Bookmarks, you have no lockfile and will likely only need to make sure all your floccus instances are either v4.x or v5.0.6+. Otherwise when using webdav the lock file is in the same directory as the bookmarks file that is used to sync.

**Comment by InfamousUser** [comment]
Using Floccus v5.0.9 and latest server and experiencing this issue...

**Comment by idzyr** [comment]
v5.0.9 with WebDAV and having this issue

**Comment by marcelklehr** [comment]
Hello everyone, sorry for the delay on this. Please, everyone since this ticket is about v5.0.5 let's all move over to #1548 if you still experience this with v5.0.8 on firefox or v5.0.9 on chrome.
