### ISSUE TITLE
Syncing with Nextcloud Bookmarks stuck without doing anything

### ISSUE THREAD

**Issue by stoneubi** [floccusaddon/floccus#972]
Windows 10 - Firefox 92.0 64 bit.

Since the update from floccus 4.7.0 to 4.8.0 sync to nextcloud 21.0.4.1 ist not working any more. The bookmarks are not synching any more. Floccus addon tries to sync but the sync cycle is turning with no effect / end. 

After deleting the addon and reinstalling floccus 4.7.0 via firefox addon page -> all versions sync is working as expected. 

A test with version 4.8.0 leads to the same result = no synching. 

I'm now on version 4.7.0 and sync works. 

Hope this can be fixed. Till that the auto update on this addon is de-activated. 

Beste regards

**Comment by marcelklehr** [comment]
Which version of the bookmarks app is installed on the server?

Does this also happen with v4.8.1?

**Comment by imforumman** [comment]
Bookmark is 10.0.0, but 4.7 worked with this version during the day today. 

(Firefox won't let me downgrade because of an unsigned extension from GitHub and the about:config switch doesn't work without some developer version... damn, Mozilla is going Apple on us, I'm starting to be really pissed off with them, but this is off topic).

**Comment by marcelklehr** [comment]
Confirmed. Will fix ASAP.

**Comment by marcelklehr** [comment]
Since bookmarks v10 + floccus v4.8 floccus uses a locking mechanism. It can happen that one client sets the lock without ever releasing it. Floccus should override the lock automaticall after half an hour. Can you try with v4.8.2?

**Comment by stoneubi** [comment]
Same here - Bookmarks App in Nextcloud is V 10.0.0 - my floccus is now 4.7 after manually "downgrade" - in fact a new installation. At the moment I only have one laptop with floccus installed. No additional clients. Is there any way / log where I can see if the lock was set?

**Comment by marcelklehr** [comment]
You can only request the lock or release it. A read method doesn't make much sense for locks. If the above command doesn't fix the problem, it's not because of locking.

**Comment by stoneubi** [comment]
Still the same on my setup. V 4.7.0 sync works perfect. All newer version are not working in my setup. Anyhow, at the moment I will stay on V4.7.0. Thanks.

**Comment by jcwinkler** [comment]
I have the same issue on my devices (2x Kiwi-Browser on Android, 2x Firefox on Windows 10) using floccus 4.8.2 and bookmarks 10.0.0. Can I help in any way by providing debug information etc.? (I have nextcloud on a shared hosting so on the server side I am limited, but maybe from the client side I can provide any kind of needed information.)

**Comment by stfnx** [comment]
OS: Windows 10 Pro 21H1 x64
Firefox: 93.0 x64
Chrome: 89.0.4389.114 (ungoogled-chromium x64)
Floccus: 4.8.2

For me syncing is working on Chrome but not on Firefox.
Waiting an hour didn't solve the issue on Firefox. Chrome is still working.

I'm not using Nextcloud Bookmarks but a WebDAV share instead.
Circle is spinning forever. After Browser restart I can click a button to see a debug log:
```
2021-10-17T08:05:54.540Z Starting sync process for account webdav@10.0.0.103
2021-10-17T08:05:54.549Z onSyncStart: begin
2021-10-17T08:05:54.549Z https://10.0.0.103:8081/Floccus/main.xbel.lock
2021-10-17T08:05:54.805Z Syncing failed with E017: Network error: Check your network connection and your account details
2021-10-17T08:05:54.806Z onSyncFail
2021-10-17T08:05:54.818Z Error Caught
2021-10-17T08:05:54.818Z [TypeError: NetworkError when attempting to fetch resource.]
```

**Comment by gothmog123** [comment]
not working again for me. seems like it looses login credentials or something. using 4.7

**Comment by marcelklehr** [comment]
> sorry not working again for me

What does this mean? Is there an error message? Is it hanging again, longer than half an hour?

**Comment by marcelklehr** [comment]
@stfnx To keep this somewhat organized please open a new issue, since you're using a different sync method.

**Comment by marcelklehr** [comment]
The update is out and floccus shouldn't get stuck anymore.

**Comment by marcelklehr** [comment]
@gothmog123 @stoneubi @imforumman @Cyberavater Is this fixed for you now?

**Comment by marcelklehr** [comment]
I've also found a bug that could cause hangs in case of unexpected status codes from the server.

**Comment by stoneubi** [comment]
Updated to V.4.8.4 and again same issue :-(

![V4 7 0 works](https://user-images.githubusercontent.com/32926093/142763634-2693c15d-8277-4025-9973-5b5af659d541.jpg)


![V4 8 4 fail](https://user-images.githubusercontent.com/32926093/142763675-95ca4baf-f55d-49a9-aec1-98ccc70d64b0.jpg)

Downloaded the log file but this log file seems to be the last working one with V.4.7.0 showing successfully sync. 

2021-11-21T13:15:22.963Z Starting sync process for account xxxxxxxx
2021-11-21T13:15:23.028Z Using "default" strategy
2021-11-21T13:15:23.123Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
2021-11-21T13:15:25.533Z Loading sparse tree as necessary
2021-11-21T13:15:25.663Z { localTreeRoot: 
2021-11-21T13:15:25.671Z { localDiff: [], serverDiff: [] }
2021-11-21T13:15:25.675Z { localPlan: [], serverPlan: [] }
2021-11-21T13:15:25.708Z Checking failsafe: 0/77=0
2021-11-21T13:15:25.742Z { reorderings: [] }
2021-11-21T13:15:25.743Z { reorderings: [] }
2021-11-21T13:15:25.813Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
2021-11-21T13:15:25.866Z Successfully ended sync process for account xxxx

Is there anything I can try to solve this isse on my setup?

Thx
Stoneubi

**Comment by stoneubi** [comment]
here some more details

![Error](https://user-images.githubusercontent.com/32926093/142764118-f2789f4d-201a-44f3-af86-80d4dbd572bf.jpg)

![V4 8 4 fail_log](https://user-images.githubusercontent.com/32926093/142764139-a28bf620-efc3-4518-96e7-0a945fe04fbd.jpg)

**Comment by marcelklehr** [comment]
@stoneubi The first two screenshots do not show anything informative or necessarily broken, afaict. Your inspector screenshot indicates that waiting half an hour should solve this problem.

**Comment by Cyberavater** [comment]
> @gothmog123 @stoneubi @imforumman @Cyberavater Is this fixed for you now?

Fixed for me in google drive.

**Comment by stoneubi** [comment]
>> The first two screenshots do not show anything informative
I wanted to show that V4.7.0 works perfect and after updateing to V4.8.4 sync is not working any more. 
Also V.4.8.x never worked in my setup. I always get locked. Even waiting for some time still the same. 

>> Just noticed there's more below the fold, so please scroll down in the inspector window.
There is just the same below. It shows the locked information again and again till sync is canceled via the "Abbruch" button.

**Comment by marcelklehr** [comment]
@stoneubi Can you try

1. Starting sync
2. Disable auto-sync
3. Wait for at least 35min and then check
  a) the floccus account overview for errors
  b) the inspector console

This may reveal an error that is hidden by the fact that floccus may try to sync again after a sync failure without giving the opportunity to see the error.

**Comment by WST1811** [comment]
I want to give Feedback. Using Floccus for a while on Nextcloud/Firefox. It works all the time great, thanks for the Tool. :) Today i found the Android App 4.8.4, working very good. ;)

In the last time i had problems with deleting bookmarks. I delete a bookmark, sync twice or more, but bookmark will not deleted on NC. Today i read the Thread here and try the solution: $ curl -u "username:password" -X DELETE https://your-nextcloud.com/index.php/apps/bookmarks/public/rest/v2/lock
It takes 2-4 seconds for execute, but after this, i sync again from Client with the deleted bookmarks, and the bookmarks where deleted on NC-Server.

Thanks again for this great Tool. ;)

**Comment by marcelklehr** [comment]
@stoneubi ?

**Comment by stoneubi** [comment]
Updated to floccus firefox addon V4.9.0. No changes on the Nextcloud Server. Sync works now :-)
